### ISSUE TITLE
No video signal. Please Help.

### ISSUE THREAD

**Issue by DKoro1** [mefistotelis/phantom-firmware-tools#34]
Hello. I have P3P. After an unsuccessful landing, he stopped sending video to the phone. Telemetry and gimbal work. As I understand it there was a damage to Nand Flash on a gimbal motherboard. (As happens in many). Is it possible to restore working capacity without changing the entire board? Changing the chip itself for example?
Thanks!

**Comment by mefistotelis** [comment]
You should be able to confirm whether the NAND is the cause by connectring your PC to DM368 serial interface via service pads.

Also, in such cases NANDs tend to show their "last breath" by working correctly for a while after you heat them up.

It should be possible to re-program the NAND, since its bootloader is likely the same as in lightbridge. And for the case it isn't - you can try backing up the chip you have. More on this:
https://github.com/mefistotelis/phantom-firmware-tools/wiki/Firmware-m0800#flashing

**Comment by DKoro1** [comment]
thanks
